import pandas as pd
import os

def generate_patients():
    patients = [
        # HIGH RISK patients (high BP + missed appts + rural + low income)
        {
            "patient_id": "P001",
            "name": "Priya M.",
            "age": 28,
            "gestational_week": 32,
            "systolic_bp": 158,
            "diastolic_bp": 102,
            "missed_appointments": 4,
            "income_level": "low",
            "transport_access": "none",
            "last_visit_days_ago": 21,
            "hemoglobin": 8.2,
            "previous_complications": "preeclampsia",
            "area": "rural",
        },
        {
            "patient_id": "P002",
            "name": "Aisha K.",
            "age": 34,
            "gestational_week": 36,
            "systolic_bp": 155,
            "diastolic_bp": 100,
            "missed_appointments": 3,
            "income_level": "low",
            "transport_access": "none",
            "last_visit_days_ago": 18,
            "hemoglobin": 8.5,
            "previous_complications": "anaemia",
            "area": "rural",
        },
        {
            "patient_id": "P003",
            "name": "Sunita D.",
            "age": 31,
            "gestational_week": 38,
            "systolic_bp": 152,
            "diastolic_bp": 98,
            "missed_appointments": 3,
            "income_level": "low",
            "transport_access": "limited",
            "last_visit_days_ago": 15,
            "hemoglobin": 8.8,
            "previous_complications": "gestational_diabetes",
            "area": "rural",
        },
        {
            "patient_id": "P004",
            "name": "Meena R.",
            "age": 29,
            "gestational_week": 34,
            "systolic_bp": 148,
            "diastolic_bp": 96,
            "missed_appointments": 3,
            "income_level": "low",
            "transport_access": "none",
            "last_visit_days_ago": 14,
            "hemoglobin": 9.0,
            "previous_complications": "preeclampsia",
            "area": "semi-urban",
        },
        # MEDIUM RISK patients
        {
            "patient_id": "P005",
            "name": "Kavitha S.",
            "age": 26,
            "gestational_week": 28,
            "systolic_bp": 135,
            "diastolic_bp": 88,
            "missed_appointments": 2,
            "income_level": "medium",
            "transport_access": "limited",
            "last_visit_days_ago": 10,
            "hemoglobin": 10.2,
            "previous_complications": "anaemia",
            "area": "semi-urban",
        },
        {
            "patient_id": "P006",
            "name": "Deepa N.",
            "age": 30,
            "gestational_week": 24,
            "systolic_bp": 130,
            "diastolic_bp": 85,
            "missed_appointments": 2,
            "income_level": "medium",
            "transport_access": "limited",
            "last_visit_days_ago": 9,
            "hemoglobin": 10.5,
            "previous_complications": "none",
            "area": "semi-urban",
        },
        {
            "patient_id": "P007",
            "name": "Lakshmi P.",
            "age": 24,
            "gestational_week": 20,
            "systolic_bp": 128,
            "diastolic_bp": 82,
            "missed_appointments": 2,
            "income_level": "low",
            "transport_access": "limited",
            "last_visit_days_ago": 8,
            "hemoglobin": 10.8,
            "previous_complications": "none",
            "area": "rural",
        },
        {
            "patient_id": "P008",
            "name": "Radha V.",
            "age": 27,
            "gestational_week": 16,
            "systolic_bp": 125,
            "diastolic_bp": 80,
            "missed_appointments": 2,
            "income_level": "medium",
            "transport_access": "good",
            "last_visit_days_ago": 7,
            "hemoglobin": 11.0,
            "previous_complications": "anaemia",
            "area": "semi-urban",
        },
        {
            "patient_id": "P009",
            "name": "Anita B.",
            "age": 33,
            "gestational_week": 30,
            "systolic_bp": 132,
            "diastolic_bp": 86,
            "missed_appointments": 1,
            "income_level": "medium",
            "transport_access": "limited",
            "last_visit_days_ago": 11,
            "hemoglobin": 10.0,
            "previous_complications": "gestational_diabetes",
            "area": "semi-urban",
        },
        {
            "patient_id": "P010",
            "name": "Padma C.",
            "age": 25,
            "gestational_week": 22,
            "systolic_bp": 120,
            "diastolic_bp": 78,
            "missed_appointments": 2,
            "income_level": "low",
            "transport_access": "none",
            "last_visit_days_ago": 12,
            "hemoglobin": 9.5,
            "previous_complications": "none",
            "area": "rural",
        },
        # LOW RISK patients
        {
            "patient_id": "P011",
            "name": "Nisha T.",
            "age": 22,
            "gestational_week": 12,
            "systolic_bp": 110,
            "diastolic_bp": 70,
            "missed_appointments": 0,
            "income_level": "high",
            "transport_access": "good",
            "last_visit_days_ago": 3,
            "hemoglobin": 12.5,
            "previous_complications": "none",
            "area": "urban",
        },
        {
            "patient_id": "P012",
            "name": "Geeta H.",
            "age": 28,
            "gestational_week": 18,
            "systolic_bp": 112,
            "diastolic_bp": 72,
            "missed_appointments": 0,
            "income_level": "high",
            "transport_access": "good",
            "last_visit_days_ago": 2,
            "hemoglobin": 12.8,
            "previous_complications": "none",
            "area": "urban",
        },
        {
            "patient_id": "P013",
            "name": "Shalini J.",
            "age": 26,
            "gestational_week": 26,
            "systolic_bp": 115,
            "diastolic_bp": 74,
            "missed_appointments": 0,
            "income_level": "medium",
            "transport_access": "good",
            "last_visit_days_ago": 4,
            "hemoglobin": 12.2,
            "previous_complications": "none",
            "area": "urban",
        },
        {
            "patient_id": "P014",
            "name": "Rekha A.",
            "age": 23,
            "gestational_week": 10,
            "systolic_bp": 108,
            "diastolic_bp": 68,
            "missed_appointments": 0,
            "income_level": "medium",
            "transport_access": "good",
            "last_visit_days_ago": 5,
            "hemoglobin": 13.0,
            "previous_complications": "none",
            "area": "urban",
        },
        {
            "patient_id": "P015",
            "name": "Pooja L.",
            "age": 29,
            "gestational_week": 14,
            "systolic_bp": 118,
            "diastolic_bp": 76,
            "missed_appointments": 1,
            "income_level": "medium",
            "transport_access": "good",
            "last_visit_days_ago": 6,
            "hemoglobin": 11.8,
            "previous_complications": "none",
            "area": "urban",
        },
    ]

    df = pd.DataFrame(patients)
    output_path = os.path.join(os.path.dirname(__file__), "patients.csv")
    df.to_csv(output_path, index=False)
    print(f"Generated {len(df)} patients → {output_path}")
    return df


if __name__ == "__main__":
    df = generate_patients()
    print(df[["name", "systolic_bp", "missed_appointments", "area", "income_level"]].to_string())
